### ISSUE TITLE
Bug #3: Creating a setInterval in the vInit function causes it to create a new interval every time the interval runs. Really weird behaviour.

### ISSUE THREAD

**Issue by JaymanMDev** [YoeriNijs/vienna#3]
![image](https://user-images.githubusercontent.com/90202232/142668568-ab4a687b-0d81-4fa3-ad88-1ef7d831371f.png)

**Comment by JaymanMDev** [comment]
It seems like vInit is really bugged, same thing is happening with requestAnimationFrame. Just really weird behaviour. And doing it in the constructor removes reactivity completely so that isn't an alternative.

**Comment by YoeriNijs** [comment]
Ah. This probably has to do something with the rebuild mechanism. I've created a possible fix for this. Prepping a release atm.

**Comment by YoeriNijs** [comment]
Bugfix released. Please reopen if the issue stil occurs.
