### ISSUE TITLE
Bug #4: the reference to `this` is not present when using requestAnimationFrame from the vInit function.

### ISSUE THREAD

**Issue by JaymanMDev** [YoeriNijs/vienna#5]
![image](https://user-images.githubusercontent.com/90202232/142678367-fa3269d7-3f15-4d4d-8c4b-91c6ebc789ff.png)
![image](https://user-images.githubusercontent.com/90202232/142678394-87c5f09c-0daa-402d-a327-c8a4ab0e3687.png)

**Comment by YoeriNijs** [comment]
It probably has something to do with the proxy that is created for change detection. See: https://stackoverflow.com/questions/66358449/why-does-proxy-break-this-binding

**Comment by YoeriNijs** [comment]
Did a bit of research on this, and it's not the proxy that breaks this binding. According to this topic, you need to bind the method call yourself: https://stackoverflow.com/questions/6065169/requestanimationframe-with-this-keyword. I guess this will work: `requestAnimationFrame(() => this.incrementCount(...));`

Please reopen if you disagree.
