### ISSUE TITLE
Bug #5: I have a counter and an input and when this counter is being used, I am unable to select and use the input. Also, requestAnimationFrame here makes my CPU and fans go crazy for some reason.

### ISSUE THREAD

**Issue by JaymanMDev** [YoeriNijs/vienna#6]
![image](https://user-images.githubusercontent.com/90202232/142679040-ce67a0c6-ee94-43df-9e39-a7c874bb36ff.png)

**Comment by YoeriNijs** [comment]
Previously, Vienna re-rendered whole components. This is wrong. Now, only dirty elements are re-rendered, so the state of your input now remains the same.
